version: "3.8"

services:
  book-store-app:
    container_name: book-store-app
    image: book-store-service
    restart: on-failure
    build: .
    depends_on:
      - book-store-db
    env_file: ./.env
    ports:
      - 8089:8080
      - 5005:5005
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://book-store-db:3306/book_store",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "1234"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
  book-store-db:
    container_name: book-store-db
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_USER=book_store
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3308:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 20s
      retries: 10